name: build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - 'docs/**'

permissions:
  contents: write # write needed to create a release
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build extension
      uses: devcontainers/ci@v0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        imageName: ghcr.io/stuartleeks/az-apim-trace-devcontainer
        cacheFrom: ghcr.io/stuartleeks/az-apim-trace-devcontainer
        runCmd: |
          make build-wheel
        env: |
          GITHUB_TOKEN
          IS_CI=1
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: wheel.zip
        path: dist/*.whl
        if-no-files-found: error